apiVersion: v1
kind: Service
metadata:
  name: rust-grpc-proxy-src
  namespace: qa
spec:
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: http
      nodePort: 30000
      port: 6789
      protocol: TCP
      targetPort: 6789
  selector:
    app: rust-grpc-proxy
  sessionAffinity: None
  type: NodePort

