apiVersion: v1
kind: Service
metadata:
  name: grpc-proxy-webhook-svc
  labels:
    app: grpc-proxy-webhook
  namespace: qa
spec:
  ports:
  - port: 443
    targetPort: 443
  selector:
    app: grpc-proxy-webhook
