apiVersion: v1
kind: ServiceAccount
metadata:
  name: grpc-proxy-webhook-sa
  labels:
    app: grpc-proxy-webhook
  namespace: qa

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: grpc-proxy-webhook-cr
  labels:
    app: grpc-proxy-webhook
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - events
  verbs:
  - "*"
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - "*"
- apiGroups:
  - autoscaling
  resources:
  - '*'
  verbs:
  - '*'

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: grpc-proxy-webhook-crb
  labels:
    app: grpc-proxy-webhook
subjects:
- kind: ServiceAccount
  name: grpc-proxy-webhook-sa
  namespace: qa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: grpc-proxy-webhook-cr
